export const ActionTypes = {
	SET_PRODUCTS: "SET_PRODUCTS",
	SELECTED_PRODUCT: "SELECTED_PRODUCT",
	REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
	ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
	INCREMENT_CART_QUANTITY: "INCREMENT_CART_QUANTITY",
	DECREMENT_CART_QUANTITY: "DECREMENT_CART_QUANTITY",
	USER_LOGGED_IN: "USER_LOGGED_IN",
	REMOVE_ITEM: "REMOVE_ITEM",
	SUB_TOTAL_OF_PRODUCTS: "SUB_TOTAL_OF_PRODUCTS",
};
